require: rubocop-rspec

AllCops:
  Exclude:
    - bin/*

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Exclude:
    - app/models/attempt.rb

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5
