require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Exclude:
    - app/models/attempt.rb

Rails/SkipsModelValidations:
  Exclude:
    - app/services/language_services/seed/operations/seed_words.rb

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 15

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/NestedGroups:
  Max: 5

RSpec/LetSetup:
  Exclude:
    - spec/requests/games_spec.rb
